### ISSUE TITLE
Formatting Issues (malformed arrow, columns not aligned)

### ISSUE THREAD

**Issue by eduncan911** [mkropat/dapper-invoice#14]
Using the `example.tex` and default `cls` as-is.

* You can see the itemized column headers not aligned.
* And the Arrow is malformed

![image](https://user-images.githubusercontent.com/104980/126910028-f6345d53-b7a2-49a1-9c1e-0d9430004743.png)

However, it occasionally does align/work when using the options below:

    -shell-escape -file-line-error -synctex=1 -interaction=nonstopmode

However, it's inconsistent.  It would work maybe 50% of the time.  Actually, at the time of this writing, it's not working at all.  Doh.

I know nothing about TeX.  I got the options [from another git repo with another TeX template](https://github.com/bammerlaan/template_blogpost_bammerlaan/blob/aac2b668a2d41f7fd53bdc118710001daf9d4fb7/GnuCash_make_invoice_English.sh#L39) that seemed to work pretty good.

**Comment by eduncan911** [comment]
Attaching the log output.  [Invoice_210725_010183.log](https://github.com/mkropat/dapper-invoice/files/6874431/Invoice_210725_010183.log)

**Comment by eduncan911** [comment]
Looks like the PR #11 fixes this issue !!

**Comment by eduncan911** [comment]
Ok, I figured out how to make it consistent on every run: I cannot delete the auto-generated `aux`,  or `out` files.

It is still malformed (arrow and columns) on a first run.  But any 2nd run and after all work fine, if I leave the aux and out files.

**Comment by eduncan911** [comment]
Saw a comment today when debugging other issues that someone had to run the parser, twice, just like I have to.

Maybe it's an issue that the `.aux` file needs to be generated first on the 1st run, and then the 2nd and all other runs work fine (as they do).

Will close this for now.

**Comment by mkropat** [comment]
Generating the temporary files on the first pass and needing to run it a second time is expected. I don't know too much about TeX so I don't have a good explanation why. All I remember is that I copied the arrow pattern from somewhere.

At least now if somebody runs into the issue in the future they have this Github issue they can find, which will point them in the right direction. Thanks for submitting the issue!
